# Generated by Django 4.2.16 on 2025-01-06 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0025_rename_target_basetarget_alter_basetarget_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
