# Generated by Django 4.2.16 on 2025-03-11 20:55

from django.db import migrations
from guardian.models import UserObjectPermission, GroupObjectPermission
from tom_targets.models import BaseTarget


def make_all_targets_public():
    BaseTarget.objects.update(permissions=BaseTarget.Permissions.PUBLIC)
    # all targets are public, so these are not needed
    UserObjectPermission.objects.filter(content_type__model='basetarget').delete()
    GroupObjectPermission.objects.filter(content_type__model='basetarget').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0025_delete_profile'),
        ('tom_targets', '0024_basetarget_permissions'),
    ]

    run_before = [
        ('tom_targets', '0025_auto_20250206_2017'),  # not strictly necessary, but makes that migration much faster
    ]

    operations = [
        migrations.RunPython(make_all_targets_public),
    ]
