# Generated by Django 4.2.16 on 2025-03-11 20:55

from django.db import migrations
from django.conf import settings

def get_target_model():
    try:
        custom_class = settings.TARGET_MODEL_CLASS
        return custom_class.split('.')[0], custom_class.split('.')[-1]
    except AttributeError:
        return 'tom_targets', 'BaseTarget'

def make_all_targets_public(apps):
    target_app, target_model = get_target_model()
    Target = apps.get_model(target_app, target_model)
    Target.objects.update(permissions=Target.Permissions.PUBLIC)


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0025_delete_profile'),
        ('tom_targets', '0024_basetarget_permissions'),
    ]

    operations = [
        migrations.RunPython(make_all_targets_public, lambda *args, **kwargs: None),
    ]
