# Generated by Django 4.2.27 on 2025-12-17 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tom_surveys', '0004_alter_surveyobservationrecord_options'),
        ('custom_code', '0025_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='facility',
            field=models.CharField(default='CSS', max_length=16),
        ),
        migrations.CreateModel(
            name='DecamThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mjd_obs', models.FloatField(null=True)),
                ('filter_name', models.CharField(max_length=8, null=True)),
                ('science_name', models.CharField(max_length=128, null=True)),
                ('thumb_template', models.BinaryField(null=True)),
                ('thumb_science', models.BinaryField(null=True)),
                ('thumb_difference', models.BinaryField(null=True)),
                ('cnnscore', models.FloatField(null=True)),
                ('snr_fphot', models.FloatField(null=True)),
                ('mag_fphot', models.FloatField(null=True)),
                ('magerr_fphot', models.FloatField(null=True)),
                ('lim_mag5', models.FloatField(null=True)),
                ('status_fphot', models.CharField(max_length=1, null=True)),
                ('in_gaia', models.CharField(max_length=32, null=True)),
                ('desi_bgs', models.CharField(max_length=32, null=True)),
                ('desi_bgs_agn', models.CharField(max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='custom_code.candidate')),
                ('observation_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tom_surveys.surveyobservationrecord')),
            ],
            options={
                'db_table': 'decam_thumbnails',
                'ordering': ['mjd_obs'],
            },
        ),
    ]
