# Generated by Django 4.2.16 on 2025-03-11 20:55

from django.db import migrations
from django.conf import settings
from guardian.models import UserObjectPermission, GroupObjectPermission

def get_target_model():
    try:
        custom_class = settings.TARGET_MODEL_CLASS
        return custom_class.split('.')[0], custom_class.split('.')[-1]
    except AttributeError:
        return 'tom_targets', 'BaseTarget'

def make_all_targets_public(apps):
    target_app, target_model = get_target_model()
    Target = apps.get_model(target_app, target_model)
    Target.objects.update(permissions=Target.Permissions.PUBLIC)

    # all targets are public, so these are not needed
    UserObjectPermission.objects.filter(content_type__model='basetarget').delete()
    GroupObjectPermission.objects.filter(content_type__model='basetarget').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0025_delete_profile'),
        ('tom_targets', '0024_basetarget_permissions'),
    ]

    run_before = [
        ('tom_targets', '0025_auto_20250206_2017'),  # not strictly necessary, but makes that migration much faster
    ]

    operations = [
        migrations.RunPython(make_all_targets_public, lambda *args, **kwargs: None),
    ]
