# Generated by Django 4.2.27 on 2026-01-28 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0026_alter_basetarget_permissions'),
        ('tom_surveys', '0004_alter_surveyobservationrecord_options'),
        ('custom_code', '0025_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyfieldcredibleregion',
            options={'ordering': ['group', 'rank_in_group', '-probability_contained']},
        ),
        migrations.CreateModel(
            name='DecamCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidatenumber', models.IntegerField(null=True)),
                ('ra', models.FloatField(null=True)),
                ('dec', models.FloatField(null=True)),
                ('elongation', models.FloatField(null=True)),
                ('fwhm', models.FloatField(null=True)),
                ('snr', models.FloatField(null=True)),
                ('mag', models.FloatField(null=True)),
                ('magerr', models.FloatField(null=True)),
                ('cx', models.FloatField(null=True)),
                ('cy', models.FloatField(null=True)),
                ('cz', models.FloatField(null=True)),
                ('classification', models.IntegerField(null=True)),
                ('mlscore', models.FloatField(null=True)),
                ('mlscore_real', models.FloatField(null=True)),
                ('mlscore_bogus', models.FloatField(null=True)),
                ('mjd_obs', models.FloatField(null=True)),
                ('filter_name', models.CharField(max_length=8, null=True)),
                ('science_name', models.CharField(max_length=128, null=True)),
                ('thumb_template', models.BinaryField(null=True)),
                ('thumb_science', models.BinaryField(null=True)),
                ('thumb_difference', models.BinaryField(null=True)),
                ('cnnscore', models.FloatField(null=True)),
                ('snr_fphot', models.FloatField(null=True)),
                ('mag_fphot', models.FloatField(null=True)),
                ('magerr_fphot', models.FloatField(null=True)),
                ('lim_mag5', models.FloatField(null=True)),
                ('status_fphot', models.CharField(max_length=1, null=True)),
                ('in_gaia', models.CharField(max_length=32, null=True)),
                ('desi_bgs', models.CharField(max_length=32, null=True)),
                ('desi_bgs_agn', models.CharField(max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observation_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decam_candidates', to='tom_surveys.surveyobservationrecord')),
                ('target', models.ForeignKey(db_column='targetid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decam_candidates', to='tom_targets.basetarget')),
            ],
            options={
                'db_table': 'decam_candidates',
                'ordering': ['-mjd_obs'],
            },
        ),
    ]
