# Generated by Django 4.2.27 on 2026-01-28 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0026_alter_basetarget_permissions'),
        ('custom_code', '0026_alter_surveyfieldcredibleregion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decamcandidate',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decam_candidates', to='tom_targets.basetarget'),
        ),
    ]
