# Generated by Django 4.2.16 on 2025-04-04 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0021_rename_target_basetarget_alter_basetarget_options'),
        ('tom_nonlocalizedevents', '0018_alter_eventcandidate_target'),
        ('custom_code', '0026_alter_candidate_target'),
    ]

    operations = [
    ]
