# Generated by Django 5.2.15 on 2026-08-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0027_alter_decamcandidate_target'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TargetListExtra',
        ),
    ]
